# Generated by Django 3.2.10 on 2023-02-20 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('born_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=1)),
                ('heigth', models.FloatField()),
                ('width', models.FloatField()),
                ('level', models.IntegerField(default=1)),
                ('water', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('sunlight', models.FloatField(default=0)),
                ('nutrients', models.FloatField(default=0)),
                ('last_time_watered', models.DateField(default=models.DateTimeField(default=django.utils.timezone.now))),
                ('last_time_fertilised', models.DateField(default=models.DateTimeField(default=django.utils.timezone.now))),
            ],
        ),
    ]
