# Generated by Django 3.2.10 on 2023-02-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantApp', '0002_alter_plant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
